ENV_NAME: "ALE/SpaceInvaders-v5"
OBS_TYPE: "grayscale"
FRAMESKIP: 4
REPEAT_ACTION_PROBABILITY: 0.0
MAX_STEPS_PER_EPISODE: 10000
EPISODES_PER_INDIVIDUAL: 1
CMA_SIGMA: 0.5
POPULATION_SIZE: null
GENERATIONS: 100
VERBOSITY_LEVEL: 1
REPEATS_PER_CONFIG: 1
CORES_PER_TASK: 4
